[package]
name = "rstationx"
version = "0.1.0"
edition = "2021"
license = "GPLv3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = ">= 0.4"
env_logger = ">= 0.9"
glium = ">= 0.31"
